# common server functions ####

#' @title Get the names of all intermediate data.frames for a given step
#' @param ind The index of the step.
#' @importFrom shiny reactiveValuesToList isolate
#' @export
get_int_dfs <- function(ind) {
  check_setup()
  req(ind)
  # we only want two reactive dependencies here: the set of stored names and the
  # workflow order (code_chain). each stored reactive is evaluated inside
  # isolate() so refreshing the dataset choices neither depends on every
  # dataset's value nor recomputes it.
  lst <- reactiveValuesToList(shinypal_env$intermediate_list)
  # restrict choices to datasets produced by steps *earlier* than this one in
  # the current workflow order, so a step can never consume a later step's (or
  # its own) output. this keeps the step dependency graph acyclic, preventing
  # reactive infinite loops and out-of-order generated code
  chain_names <- names(shinypal_env$code_chain())
  pos <- match(paste0("step_", ind), chain_names)
  # a step still being built isn't in the chain yet; treat it as appended last
  if (is.na(pos)) pos <- length(chain_names) + 1L
  earlier_inds <- sub("^step_", "", chain_names[seq_len(pos - 1L)])
  lst <- lst[sub(".*_(\\d+)$", "\\1", names(lst)) %in% earlier_inds]
  lst |>
    Filter(f = Negate(is.null)) |>
    Filter(f = function(el) is.data.frame(isolate(el()))) |>
    names()
}

#' @title Show a modal with a reactable data.frame
#' @param input The shiny input object.
#' @param output The shiny output object.
#' @param ind The index of the step.
#' @param df_name The name of the data.frame to be displayed.
#' @importFrom shiny observeEvent showModal modalDialog
#' @importFrom DT DTOutput renderDataTable datatable
#' @importFrom shinycssloaders withSpinner
#' @export
df_modal_observe <- function(input, output, ind, df_name) {
  check_setup()
  req(input, output, ind, df_name)
  observeEvent(input[[paste0("df_modal_", ind)]], {
    showModal(modalDialog(
      withSpinner(DTOutput(paste0("df_", ind))),
      size = "l", easyClose = TRUE
    ))
    output[[paste0("df_", ind)]] <- renderDataTable(datatable(
      isolate(shinypal_env$intermediate_list[[df_name]]()),
      style = "bootstrap5",
      options = list(
        autoWidth = TRUE,
        columnDefs = list(list(width = '25px', targets = 0),
                          list(width = '150px', targets = '_all')),
        scrollX = TRUE,
        scrollY = "70dvh",
        scrollCollapse = TRUE,
        pageLength = 25
      )
    ))
  }, ignoreInit = TRUE)
}

#' @title Keep a `selectInput` of intermediate data.frames up-to-date
#' @param input The shiny input object.
#' @param ind The index of the step.
#' @importFrom shiny req observe isolate updateSelectInput
#' @importFrom rlang `%||%`
#' @export
df_select_observe <- function(input, ind) {
  check_setup()
  req(input, ind)
  # choices should always include all intermediate data.frames
  observe({
    choices <- get_int_dfs(ind) %||% character(0)
    # try to preserve the old selected dataset name
    old_df <- isolate(input[[paste0("dataset_", ind)]])
    if (!is.null(old_df) && old_df %in% choices) {
      selected <- old_df
    } else {
      selected <- NULL
    }
    # update choices but maintain selected
    updateSelectInput(inputId = paste0("dataset_", ind), choices = choices,
                      selected = selected)
  })
}

#' @title Keep a `varSelectInput` of data.frame column names up-to-date
#' @param input The shiny input object.
#' @param ind The index of the step.
#' @param inputId The id of the [shiny::varSelectInput()] object.
#' @importFrom shiny req observeEvent isolate updateVarSelectInput
#' @importFrom rlang as_string
#' @export
column_select_observe <- function(input, ind, inputId) {
  check_setup()
  req(input, ind, inputId)
  observeEvent(input[[paste0("dataset_", ind)]], {
    df_name <- input[[paste0("dataset_", ind)]]
    choices <- colnames(isolate(get_int_data(df_name)()))
    # try to preserve the old selected column name
    old_col <- isolate(input[[inputId]])
    if (!is.null(old_col) && as_string(old_col) %in% choices) {
      selected <- old_col
    } else {
      selected <- NULL
    }
    updateVarSelectInput(inputId = inputId,
                          data = isolate(get_int_data(df_name)()),
                          selected = selected)
  }, ignoreInit = TRUE)
}

#' @title Add an observer to a copy button
#' @description
#'   Generates an event observer that watches for when a copy button is clicked.
#'   Upon clicking, the `code_expr` is evaluated and copied to the clipboard
#'   using [clipr::write_clip()].
#' @param input The shiny input object.
#' @param output The shiny output object.
#' @param ind The index of the step.
#' @param code_expr An expression (generated by [rlang::expr()] that, when
#'   evaluated, returns content to be copied (such as the output from
#'   [shinymeta::expandChain()].
#' @importFrom shiny observeEvent
#' @importFrom clipr write_clip
#' @export
clip_observe <- function(input, output, ind, code_expr) {
  observeEvent(input[[paste0("copy_", ind)]], {
    write_clip(eval(code_expr), allow_non_interactive = TRUE)
  })
}

#' @title Observe a file input to be included in the download bundle
#' @param input The shiny input object.
#' @param inputId The id of the [shiny::fileInput()] object.
#'   of the file in the code.
#' @importFrom shiny observeEvent isolate
#' @importFrom rlang inject set_names
#' @export
file_observe <- function(input, inputId) {
  check_setup()
  observeEvent(input[[inputId]], {
    file_obj <- isolate(input[[inputId]])
    shinypal_env$include_files[[inputId]] <-
      set_names(list(file_obj$datapath), file_obj$name)
  }, ignoreInit = TRUE)
}

#' @title Get the expanded code chunk for a registered step
#' @description
#'   Returns the code chunk for `ind`, expanded with a shared context across
#'   all currently-registered steps. Use this inside a reactive consumer
#'   (e.g., `renderPrint()`, `observeEvent()`) to display or copy a step's
#'   code. The chunk is rebuilt whenever any dependency changes.
#' @param ind The index of the step.
#' @returns A code object suitable for printing or passing to
#'   [shinymeta::displayCodeModal()], or `NULL` if the step is not registered.
#' @export
get_chunk <- function(ind) {
  check_setup()
  chunk <- shinypal_env$chunks()[[paste0("step_", ind)]]
  # re-throw any per-step error so the consuming reactive's req()/validate()
  # semantics handle it normally (silent errors stay silent, etc.)
  if (inherits(chunk, "condition")) stop(chunk)
  chunk
}

#' @title Set an intermediate data object
#' @param obj A reactive data object to store.
#' @param name A name to store data object as.
#' @importFrom shiny req
#' @export
set_int_data <- function(obj, name) {
  check_setup()
  req(obj, name)
  shinypal_env$intermediate_list[[name]] <- obj
}

#' @title Get an intermediate data object
#' @param name The name of the data object to retrieve.
#' @importFrom shiny req
#' @export
get_int_data <- function(name) {
  check_setup()
  req(name)
  # make sure the item still exists in the list
  req(shinypal_env$intermediate_list[[name]])
  shinypal_env$intermediate_list[[name]]
}

#' @title Get the next workflow step index
#' @description
#'   Returns a unique, monotonically increasing index for a new workflow step.
#'   Each call increments a server-side counter. The counter is initialised by
#'   [shinypal_setup()] and is deliberately never reset while the session is
#'   running.
#' @returns A single positive integer to use as the new step's index.
#' @export
next_step_index <- function() {
  check_setup()
  shinypal_env$step_counter <- shinypal_env$step_counter + 1
  shinypal_env$step_counter
}

clear_workflow <- function() {
  check_setup()
  shinypal_env$report_list(tagList())
  shinypal_env$code_chain(list())
  shinypal_env$libraries_chain(list())
  shinypal_env$ec_subs(list())
  for (name in names(reactiveValuesToList(shinypal_env$intermediate_list))) {
    shinypal_env$intermediate_list[[name]] <- NULL
  }
  for (name in names(reactiveValuesToList(shinypal_env$include_files))) {
    shinypal_env$include_files[[name]] <- NULL
  }
}
