# common server functions ####

#' @title Get the names of all intermediate data.frames for a given step
#' @param ind The index of the step.
#' @importFrom shiny reactiveValuesToList
#' @export
get_int_dfs <- function(ind) {
  # TODO: there's an infinite loop here when you have a dataset that depends
  # on a dataset that is part of a step that depends on the original dataset
  check_setup()
  req(ind)
  lst <- reactiveValuesToList(shinypal_env$intermediate_list)
  lst[!grepl(paste0("_", ind), names(lst))] |>
    Filter(f = Negate(is.null)) |>
    Filter(f = function(el) is.data.frame(el())) |>
    names()
}

#' @title Show a modal with a reactable data.frame
#' @param input The shiny input object.
#' @param output The shiny output object.
#' @param ind The index of the step.
#' @param df_name The name of the data.frame to be displayed.
#' @importFrom shiny observeEvent showModal modalDialog
#' @importFrom reactable reactableOutput reactable renderReactable colDef
#' @export
df_modal_observe <- function(input, output, ind, df_name) {
  check_setup()
  req(input, output, ind, df_name)
  observeEvent(input[[paste0("df_modal_", ind)]], {
    showModal(modalDialog(
      reactableOutput(paste0("df_", ind)), size = "l", easyClose = TRUE
    ))
    output[[paste0("df_", ind)]] <- renderReactable({
      reactable(isolate(shinypal_env$intermediate_list[[df_name]]()),
                defaultColDef = colDef(
                  cell = function(value) format(value, nsmall = 1),
                  align = "center",
                  minWidth = 150,
                  headerStyle = list(background = "#f7f7f8", cursor = "pointer")
                ),
                defaultPageSize = 25)
    })
  }, ignoreInit = TRUE)
}

#' @title Keep a `selectInput` of intermediate data.frames up-to-date
#' @importFrom shiny req observe isolate updateSelectInput
#' @importFrom rlang `%||%`
#' @export
df_select_observe <- function(input, ind) {
  check_setup()
  req(input, ind)
  # choices should always include all intermediate data.frames
  observe({
    choices <- get_int_dfs(ind) %||% character(0)
    # try to preserve the old selected dataset name
    old_df <- isolate(input[[paste0("dataset_", ind)]])
    if (!is.null(old_df) && old_df %in% choices) {
      selected <- old_df
    } else {
      selected <- NULL
    }
    # update choices but maintain selected
    updateSelectInput(inputId = paste0("dataset_", ind), choices = choices,
                      selected = selected)
  })
}

#' @title Keep a `varSelectInput` of data.frame column names up-to-date
#' @param input The shiny input object.
#' @param ind The index of the step.
#' @param inputId The id of the [shiny::varSelectInput()] object.
#' @importFrom shiny req observeEvent isolate updateVarSelectInput
#' @importFrom rlang as_string
#' @export
column_select_observe <- function(input, ind, inputId) {
  check_setup()
  req(input, ind, inputId)
  observeEvent(input[[paste0("dataset_", ind)]], {
    df_name <- input[[paste0("dataset_", ind)]]
    choices <- colnames(isolate(get_int_data(df_name)()))
    # try to preserve the old selected column name
    for (col in 1:2) {
      old_col <- isolate(input[[inputId]])
      if (!is.null(old_col) && as_string(old_col) %in% choices) {
        selected <- old_col
      } else {
        selected <- NULL
      }
      updateVarSelectInput(inputId = inputId,
                           data = isolate(get_int_data(df_name)()),
                           selected = selected)
    }
  }, ignoreInit = TRUE)
}

#' @title Add an observer to a copy button
#' @description
#'   Generates an event observer that watches for when a copy button is clicked.
#'   Upon clicking, the `code_expr` is evaluated and copied to the clipboard
#'   using [clipr::write_clip()].
#' @param input The shiny input object.
#' @param output The shiny output object.
#' @param ind The index of the step.
#' @param code_expr An expression (generated by [rlang::expr()] that, when
#'   evaluated, returns content to be copied (such as the output from
#'   [shinymeta::expandChain()].
#' @importFrom shiny observeEvent
#' @importFrom clipr write_clip
#' @export
clip_observe <- function(input, output, ind, code_expr) {
  observeEvent(input[[paste0("copy_", ind)]], {
    write_clip(eval(code_expr), allow_non_interactive = TRUE)
  })
}

#' @title Observe a file input to be included in the download bundle
#' @param input The shiny input object.
#' @param inputId The id of the [shiny::fileInput()] object.
#'   of the file in the code.
#' @importFrom shiny observeEvent isolate
#' @importFrom rlang inject set_names
#' @export
file_observe <- function(input, inputId) {
  check_setup()
  observeEvent(input[[inputId]], {
    file_obj <- isolate(input[[inputId]])
    shinypal_env$include_files[[inputId]] <-
      set_names(list(file_obj$datapath), file_obj$name)
  }, ignoreInit = TRUE)
}

#' @title Expand code objects with a shared context
#' @description
#'   A wrapper for [shinymeta::expandChain()] that uses a shared expansion
#'   context specific to shinypal.
#' @inherit shinymeta::expandChain
#' @importFrom shinymeta expandChain
#' @export
expandChain_shared <- function(...) {
  expandChain(..., .expansionContext = shinypal_env$shared_ec)
}

#' @title Set an intermediate data object
#' @param obj A reactive data object to store.
#' @param name A name to store data object as.
#' @importFrom shiny req
#' @export
set_int_data <- function(obj, name) {
  check_setup()
  req(obj, name)
  shinypal_env$intermediate_list[[name]] <- obj
}

#' @title Get an intermediate data object
#' @param name The name of the data object to retrieve.
#' @importFrom shiny req
#' @export
get_int_data <- function(name) {
  check_setup()
  req(name)
  shinypal_env$intermediate_list[[name]]
}

clear_workflow <- function() {
  check_setup()
  shinypal_env$report_list(tagList())
  shinypal_env$code_chain(list())
  shinypal_env$libraries_chain(list())
  shinypal_env$ec_subs(list())
  for (name in names(reactiveValuesToList(shinypal_env$intermediate_list))) {
    shinypal_env$intermediate_list[[name]] <- NULL
  }
  for (name in names(reactiveValuesToList(shinypal_env$include_files))) {
    shinypal_env$include_files[[name]] <- NULL
  }
  updateNumericInput(inputId = "accordion_version", value = "1")
}
